build:
  tags:
    - docker
    - linux
  image: jedbrown/mpich
  script:
    - mkdir -p _build/debug
    - cd _build/debug
    - CC=mpicc FC=mpif90 cmake -DCMAKE_BUILD_TYPE=Debug ../..
    - cmake --build .
    - ctest