stages:
  - build

linux:
  stage: build
  tags:
    - docker
    - linux
  image: fedora:33
  before_script:
    - dnf install -y gcc gcc-gfortran gcovr openmpi-devel cmake
    - export PATH=/usr/lib64/openmpi/bin/:$PATH
    - export OMPI_ALLOW_RUN_AS_ROOT=1
    - export OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1
    - export MMA_MPI_RUN_FLAG="-oversubscribe"

  script:
    - mkdir -p _build
    - cd _build
    - CC=mpicc FC=mpif90 cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=1 -DCMAKE_C_FLAGS=--coverage ..
    - make
    - make test
    - mkdir -p ../coverage
    - gcovr -r .. src
    - gcovr -r .. src --xml=../coverage.xml --html-details=../coverage/coverage.html
  coverage: '/^TOTAL.*\s+(\d+\%)$/'
  artifacts:
    reports:
      cobertura: coverage.xml
    expose_as: 'Coverage Report'
    paths:
      - coverage/
