stages:
  - build
  - test

build linux:
  stage: build
  tags:
    - docker
    - linux
  image: jedbrown/mpich
  script:
    - mkdir -p _build/debug
    - cd _build/debug
    - CC=mpicc FC=mpif90 cmake -DCMAKE_BUILD_TYPE=Debug ../..
    - cmake --build .
  artifacts:
    paths:
      - _build

test linux:
  stage: test
  tags:
    - docker
    - linux
  image: jedbrown/mpich
  script:
    - cd _build/debug
    - ctest
